# Generated by Django 3.2.7 on 2021-10-03 15:11

from django.conf import settings
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='name', primary_key=True, serialize=False)),
                ('name', django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Type Name')),
                ('cost', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Training Type Cost')),
            ],
            options={
                'verbose_name': 'Training Type',
                'verbose_name_plural': 'Training Types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('rank', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Rank')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_words', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User word',
                'verbose_name_plural': 'User words',
                'ordering': ('rank',),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, max_length=255, populate_from='english', primary_key=True, serialize=False)),
                ('english', django.contrib.postgres.fields.citext.CICharField(max_length=255, unique=True, verbose_name='Word in english')),
                ('russian', django.contrib.postgres.fields.citext.CICharField(max_length=255, verbose_name='Word in russian')),
                ('categories', models.ManyToManyField(related_name='words', related_query_name='word', to='training.Category')),
                ('users', models.ManyToManyField(related_name='words', related_query_name='word', through='training.UserWord', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ('english',),
            },
        ),
        migrations.AddField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_words', to='training.word'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trainings', to='training.trainingtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', related_query_name='training', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Training',
                'verbose_name_plural': 'Trainings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userword',
            unique_together={('user', 'word')},
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.training')),
                ('user_word', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='training.userword')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'unique_together': {('training', 'user_word')},
            },
        ),
    ]
