# Generated by Django 3.2.7 on 2021-11-19 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userword',
            name='learned_times',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Word learned times'),
        ),
    ]
