# Generated by Django 3.2.7 on 2021-12-12 12:29

import config.settings.common.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=config.settings.common.paths._default_media_path, verbose_name='Image'),
        ),
    ]
