# Generated by Django 3.2.7 on 2022-01-02 10:55
from django.contrib.postgres.operations import TrigramExtension

import apps.training.models.training
from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0002_category_image'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddField(
            model_name='trainingtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.training.models.training.training_type_upload_to, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='questions_count',
            field=models.PositiveIntegerField(default=0, help_text='How much questions must be in training', verbose_name='Questions count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='words_per_question_count',
            field=models.PositiveIntegerField(default=0, help_text='How much questions must be in training', verbose_name='Words per question count'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='cost',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='trainingtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Type Name'),
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('user', 'type')},
        ),
    ]
