# Generated by Django 3.2.7 on 2022-02-20 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20220102_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='user_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='questions', to='training.userword'),
        ),
        migrations.CreateModel(
            name='TrainingTypeUserWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='chosen_words', to='training.trainingtype')),
                ('user_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_words', related_query_name='chosen_words', to='training.userword')),
            ],
            options={
                'verbose_name': 'Training Type User Word',
                'verbose_name_plural': 'Training Types User Words',
            },
        ),
    ]
