# Generated by Django 3.2.7 on 2022-03-01 13:56

from django.db import migrations, models
from apps.training import constants


def create_training_types(apps, schema_editor):
    """Create training types with hardcoded ids."""
    TrainingType = apps.get_model("training", "trainingtype")
    training_types = []
    for train_type_data in constants.TRAINING_TYPES:
        training_types.append(TrainingType(**train_type_data))
    TrainingType.objects.bulk_create(
        objs=training_types,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('training', '0004_auto_20220220_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtype',
            name='id',
            field=models.CharField(
                max_length=20,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True
            ),
        ),
        migrations.AddField(
            model_name='trainingtype',
            name='words_can_be_chosen',
            field=models.BooleanField(default=True, verbose_name='Words can be chosen'),
        ),
        migrations.RunPython(
            code=create_training_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
