# Generated by Django 3.2.7 on 2022-03-07 09:27

import config.settings.common.paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_word_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=config.settings.common.paths._default_media_path, verbose_name='Image'),
        ),
    ]
