# Generated by Django 3.2.7 on 2022-05-19 10:48

import apps.training.models.training
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_alter_trainingtypeuserword_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingtype',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to=apps.training.models.training.training_type_upload_to, verbose_name='Image'),
        ),
    ]
