# Generated by Django 3.2.7 on 2022-05-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_trainingtype_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
