# Generated by Django 3.2.7 on 2021-12-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=30, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
